### ISSUE TITLE
"New discussion" button does not appear to some logged in users

### ISSUE THREAD

**Issue by traderprofile** [processing/processing-forum#16]
help... im new at github... i want to create an issue.. but i cant... the button New Issue its not there... i already confirmed my email, what do i have to do?

**Comment by volkanozcan2** [comment]
Same here !!!

**Comment by GABBAR1947** [comment]
Can someone look into this issue. there appears to be no "new discussion" button when logged in to the forum. Is it a browser issue or what?

**Comment by alignedleft** [comment]
The "New discussion" button *does* appear for me, using Safari 10 on Mac OS 10.10:

![screen shot 2017-03-01 at 10 18 17 am](https://cloud.githubusercontent.com/assets/1034002/23474415/91142e1e-fe68-11e6-945c-981e5ca7de47.png)

Anyone else experiencing this issue, please post your browser, version, and OS, and a screenshot, if possible, so we can look into this. Otherwise, we'll close this issue, as I see people are continuing to post on the forums (evidence that it is working). Thanks!

**Comment by GABBAR1947** [comment]
[
<img width="1259" alt="screen shot 2017-03-02 at 12 39 26 am" src="https://cloud.githubusercontent.com/assets/9786291/23476427/bcf2b870-fee0-11e6-8683-596d23547349.png">
](url)
macOS Sierra- 10.12.3
Browser - safari 10.0.3

**Comment by Killthebug** [comment]
![screen shot 2017-03-02 at 7 59 22 pm](https://cloud.githubusercontent.com/assets/10692240/23511351/c6fbbc52-ff82-11e6-9d8d-9b68d251ffd9.png)

macOS Sierra
Safari

**Comment by GABBAR1947** [comment]
@alignedleft where is the source code for the forum ?

**Comment by alignedleft** [comment]
Code lives only on the server, not here in GitHub, but the forums run [Vanilla](https://vanillaforums.com/en/software/).

**Comment by fjenett** [comment]
Your accounts were not yet fully activated hence you were not allowed to post.

**Comment by GABBAR1947** [comment]
@fjenett awesome, it works now !

**Comment by MatteoCarotta** [comment]
@fjenett Hi, I'm experiencing this problem as well on Firefox 58.0.1 on Ubuntu. Can you check if my account is fully activated? Thanks in advance
